sales/urls.py
from django.urls import path

from . import views

app_name = 'sales'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/',
         views.remove_from_cart, name='remove-from-cart'),
    path('order/', views.OrderSummaryView.as_view(), name='order'),
    path('increase-quantity/<slug>/',
         views.increase_quantity, name='increase-quantity'),
    path('decrease-quantity/<slug>/',
         views.decrease_quantity, name='decrease-quantity'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
]

victorian_fireplaces/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('sales.urls', namespace='sales')),
]

sales/models.py
from distutils.command.upload import upload
from allauth.utils import get_user_model
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField

User = get_user_model()

CATEGORY_CHOICES = (
    ('SU', 'Surrounds'),
    ('IN', 'Inserts'),
    ('HE', 'Hearths'),
    ('PA', 'Parts'),
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    description = models.CharField(max_length=1000, blank=True)
    category = models.CharField(
        choices=CATEGORY_CHOICES, max_length=10, default='PA')
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='media')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('sales:product', kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse('sales:add-to-cart', kwargs={'slug': self.slug})

    def get_price(self):
        if (self.discount_price):
            return self.discount_price
        return self.price


class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.item.title) + str(self.quantity)

    def get_total_price(self):
        if (self.item.discount_price):
            return self.quantity * self.item.discount_price
        return self.quantity * self.item.price

    def get_amount_saved(self):
        if (self.item.discount_price):
            return self.quantity*self.item.price - self.quantity * self.item.discount_price
        return 0


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True,
                                        null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True,
                                null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_price()
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    postcode = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    price = models.FloatField()
    stripe_charge_id = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}
  <title>Victorian Fireplaces</title>
  <!-- Bootstrap -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- MDB-->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Custom Styles -->
  <link href="{% static 'css/style.css' %} " rel="stylesheet">
  
  {% block header %}
  {% endblock %}
  </style>
</head>
<body>
  <!-- Nav -->
  <nav class="navbar navbar-light fixed-top navbar-expand-lg bg-light scrolling-navbar">
    <div class="container">
      <!-- Brand -->
      <a href="{% url 'sales:home' %}" class="navbar-brand">
        <strong>Victorian Fireplace Company</strong>
      </a>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            {% if user.is_authenticated%}
            <a href="{% url 'sales:checkout' %}" class="nav-link">Checkout</a>
            <a href="{% url 'account_logout' %}" class="nav-link">Logout</a>
            {% else %}
            <a href="{% url 'account_login' %}" class="nav-link">Login</a>
            <a href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div style="padding-top: 60px;">
  {% if messages %}
    {% for message in messages %}
    <div class="alert" role="alert">
      {{message}}
    </div>
    {% endfor %}
  {% endif %}
  </div>

  {% block content %}
  {% endblock %}

  <!-- Footer -->
  <footer class="page-footer fix-down text-center font-small mt-4">
    <div class="footer-copyright">© 2022 Fred Gryson</div>
  </footer>
  <!-- Scripts -->
  {% block scripts %}
  {% endblock scripts %}
  <script src="{% static 'js/jquery-3.6.0.min.js' %} "></script>
  <!-- Bootstrap -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB -->
  <script src="{% static 'js/mdb.min.js' %} "></script>
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/2cdcea010c.js" crossorigin="anonymous"></script>
  <!-- Popper JS -->
  <script src="https://unpkg.com/@popperjs/core@2"></script>
</body>
</html>

templates/checkout.html
{% extends 'base.html' %}

{% block content %}
<main >
  <div class="container mt-5">
    <h2 class="my-5 h2 text-center">Checkout form</h2>
    <div class="row">
      <div class="col-md-8 mb-4">
        <div class="card">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endif %}
          <form action="{%url 'sales:checkout' %}" method="POST" class="card-body">
            {% csrf_token %}
            <h3>Shipping address</h3>
            <div class='hideable_shipping_form'>

              <div class="md-form mb-5">
                <input type='text' placeholder='Ballyboffin Lane' id='street_address' name='street_address' class='form-control' />
                <label for="street_address" class="">Address</label>
                {{ error|escape }}
              </div>
              
              <div class="md-form mb-5">
                <input type='text' placeholder='House name' id='apartment_address' name='apartment_address' class='form-control' />
                <label for="apartment_address" class="">Address 2 (optional)</label>
              </div>
              
              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="postcode">Post Code</label>
                  <input type='text' placeholder='Post code' id='postcode' name='postcode' class='form-control' />
                  <div class="invalid-feedback">
                    Post code required.
                  </div>
                </div>
              </div>
              
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="same_shipping_address" id="same_billing_address">
                <label class="custom-control-label" for="same_shipping_address">Billing address is the same as my shipping address</label>
              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="save_info" id="save_info">
                <label class="custom-control-label" for="save_info">Save as default shipping address</label>
              </div>
              
            </div>

            <hr class="mb-4">
            
            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
            
          </form>
        </div>
      </div>

      <div class="col-md-4 mb-4">
        {% include "order-summary.html" %}
      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Carousel wrapper -->
<div id="carousel" class="carousel slide carousel-fade" data-mdb-ride="carousel">
    <!-- Indicators -->
    <div class="carousel-indicators">
      <button
        type="button"
        data-mdb-target="#carousel"
        data-mdb-slide-to="0"
        class="active"
        aria-current="true"
        aria-label="Slide 1"
      ></button>
      <button
        type="button"
        data-mdb-target="#carousel"
        data-mdb-slide-to="1"
        aria-label="Slide 2"
      ></button>
      <button
        type="button"
        data-mdb-target="#carousel"
        data-mdb-slide-to="2"
        aria-label="Slide 3"
      ></button>
    </div>
  
    <!-- Inner -->
    <div class="carousel-inner">
      <!-- Single item -->
      <div class="carousel-item active">
        <img src="{% static 'img/AlcoveW.jpeg' %}" class="d-block w-100" alt="To set"/>
        <div class="carousel-caption d-none d-md-block">
          <h5>Victorian Fireplace Company</h5>
        </div>
      </div>
  
      <!-- Single item -->
      <div class="carousel-item">
        <img src="{% static 'img/MarbleW.jpeg' %}" class="d-block w-100" alt="To set"/>
        <div class="carousel-caption d-none d-md-block">
          <h5>Fireplace Fitting</h5>
        </div>
      </div>
  
      <!-- Single item -->
      <div class="carousel-item">
        <img src="{% static 'img/InsertW.jpeg' %}" class="d-block w-100" alt="To set"/>
        <div class="carousel-caption d-none d-md-block">
          <h5>Fireplace Restoration</h5>
        </div>
      </div>
    </div>
    <!-- Inner -->
  
    <!-- Controls -->
    <button class="carousel-control-prev" type="button" data-mdb-target="#carousel" data-mdb-slide="prev">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
      </svg>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-mdb-target="#carousel" data-mdb-slide="next">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
      </svg>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <!-- Carousel wrapper -->

  <!--Main layout-->
  <main>
    <div class="container mt-4">

      <!--Section: Products-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row">

          <!--Fourth column-->
          {% for item in item_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->

            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{item.image.url}}" class="card-img-top"
                  style= "object-fit: cover;" alt="Not available image">

                <a href = "{{item.get_absolute_url}}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5> {{item.get_category_display}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{item.get_absolute_url}}" class="dark-grey-text">{{item.title}}</a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  {% if item.discount_price %}
                  <strong>{{item.discount_price}}€</strong>
                  {% else %}
                  <strong>{{item.price}}€</strong>
                  {% endif %}
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->


          </div>
          <!--Fourth column-->
          {% endfor %}
        </div>
        <!--Grid row-->

      

      </section>
      <!--Section: Products v.3-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center">
        <ul class="pagination pg-blue">

            <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item ">
            <a class="page-link" href="?page= {{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page= {{page_obj.number}}">{{page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>


          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->
      {% endif %}

    </div>
  </main>

{% endblock %}

templates/order-summary.html
<div class="col-md-12 mb-4">
  <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
  </h4>
  <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
      </div>
      <span class="text-muted">${{ order_item.get_total_price }}</span>
    </li>
    {% endfor %}
    <li class="list-group-item d-flex justify-content-between">
      <span>Total (EUR)</span>
      <strong>${{ order.get_total }}</strong>
    </li>
  </ul>
</div>

templates/order.html
{% extends 'base.html' %}

{% block content %}
<main class=" pt-5">
    <div class="container">
        <table class="table ">
            <thead class="thead-dark ">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Item Title</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total Price</th>
              </tr>
            </thead>
            <tbody>
              {% for order_item in object.items.all %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>
                  <a href = "{% url 'sales:product' slug=order_item.item.slug %}"> {{order_item.item.title}} </a>
                </td>
                <td>€{{order_item.item.get_price}} </td>
                <td>
                  <a href="{% url 'sales:decrease-quantity' slug=order_item.item.slug %}"> <i class="fas fa-minus"></i></a>
                  {{order_item.quantity}}
                  <a href="{% url 'sales:increase-quantity' slug=order_item.item.slug %}"><i class="fas fa-plus"></i> </a>
                </td>
                <td>
                  {% if order_item.item.discount_price %}
                  €{{order_item.get_total_price}}
                  <span class="badge badge-primary"> Saving €{{order_item.get_amount_saved}}</span>
                  {%else%}
                  €{{order_item.get_total_price}}
                  {% endif %}
                </td>
              </tr>
              {% empty %}
              <p>No Items in Cart</p>
              {% endfor %}
              <tr>
                  <td colspan="4">
                      <b>Order Total</b>
                  </td>
                  <td>
                      <b>€{{object.get_total}}</b>
                  </td>
              </tr>
              <tr>
                  <td colspan="5">
                      {% if object.items.all.count > 0 %}
                      <a href="/checkout" class="btn btn-warning float-right ml-2">Checkout</a>
                      {% endif %}
                      <a href="/" class="btn btn-primary float-right">Go Back</a>
                  </td>
              </tr>
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

templates/payment.html
{% extends 'base.html' %}

{%block header %}
<style>
  #stripeBtnLabel {
    font-family: "Helvetica Neue", Helvetica, sans-serif;
    font-size: 16px;
    font-variant: normal;
    padding: 0;
    margin: 0;
    -webkit-font-smoothing: antialiased;
    font-weight: 500;
    display: block;
  }

  #stripeBtn {
    border: none;
    border-radius: 4px;
    outline: none;
    text-decoration: none;
    color: #fff;
    background: #32325d;
    white-space: nowrap;
    display: inline-block;
    height: 40px;
    line-height: 40px;
    box-shadow: 0 4px 6px rgba(50, 50, 93, .11), 0 1px 3px rgba(0, 0, 0, .08);
    border-radius: 4px;
    font-size: 15px;
    font-weight: 600;
    letter-spacing: 0.025em;
    text-decoration: none;
    -webkit-transition: all 150ms ease;
    transition: all 150ms ease;
    float: left;
    width: 100%
  }

  button:hover {
    transform: translateY(-1px);
    box-shadow: 0 7px 14px rgba(50, 50, 93, .10), 0 3px 6px rgba(0, 0, 0, .08);
    background-color: #43458b;
  }

  .stripe-form {
    padding: 5px 30px;
  }

  #card-errors {
    height: 20px;
    padding: 4px 0;
    color: #fa755a;
  }

  .stripe-form-row {
    width: 100%;
    float: left;
    margin-top: 5px;
    margin-bottom: 5px;
  }

  /**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
  .StripeElement {
    box-sizing: border-box;

    height: 40px;

    padding: 10px 12px;

    border: 1px solid transparent;
    border-radius: 4px;
    background-color: white;

    box-shadow: 0 1px 3px 0 #e6ebf1;
    -webkit-transition: box-shadow 150ms ease;
    transition: box-shadow 150ms ease;
  }

  .StripeElement--focus {
    box-shadow: 0 1px 3px 0 #cfd7df;
  }

  .StripeElement--invalid {
    border-color: #fa755a;
  }

  .StripeElement--webkit-autofill {
    background-color: #fefde5 !important;
  }

  .current-card-form {
    display: none;
  }
</style>

{% endblock %}

{% block content %}

<main>
  <div class="container">

    <h2 class="my-5 h2 text-center">Payment</h2>

    <div class="row">

      <div class="col-md-12 mb-4">
        <div class="card">

          {% if card %}
          <div style="padding: 5px 30px;">
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_card" id="use_default_card">
              <label class="custom-control-label" for="use_default_card">Use default card:
                **** **** **** {{ card.last4 }}
                <span>Exp: {{ card.exp_month }}/{{ card.exp_year }}</span></label>
            </div>
          </div>
          {% endif %}

          <div class="current-card-form">
            <form action="." method="post" class="stripe-form">
              {% csrf_token %}
              <input type="hidden" name="use_default" value="true">
              <div class="stripe-form-row">
                <button id="stripeBtn">Submit Payment</button>
              </div>
              <div id="card-errors" role="alert"></div>
            </form>
          </div>

          <div class="new-card-form">
            <form action="." method="post" class="stripe-form" id="stripe-form">
              {% csrf_token %}
              <div class="stripe-form-row" id="creditCard">
                <label for="card-element" id="stripeBtnLabel">
                  Credit or debit card
                </label>
                <div id="card-element" class="StripeElement StripeElement--empty">
                  <div class="__PrivateStripeElement"
                    style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;">
                    <iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame5"
                      allowpaymentrequest="true"
                      src="https://js.stripe.com/v3/elements-inner-card-19066928f2ed1ba3ffada645e45f5b50.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js&amp;controllerId=__privateStripeController1"
                      title="Secure payment input frame"
                      style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; height: 19.2px;"></iframe><input
                      class="__PrivateStripeElement-input" aria-hidden="true" aria-label=" " autocomplete="false"
                      maxlength="1"
                      style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
                  </div>
                </div>
              </div>
              <div class="stripe-form-row">
                <button id="stripeBtn">Submit Payment</button>
              </div>
              <div class="stripe-form-row">
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="save" id="save_card_info">
                  <label class="custom-control-label" for="save_card_info">Save for future purchases</label>
                </div>
              </div>
              <div id="card-errors" role="alert"></div>
            </form>
          </div>

        </div>
      </div>

      {% include "order-summary.html" %}

    </div>

  </div>
</main>


{% endblock %}


{% block extra_scripts %}
<script src="https://js.stripe.com/v3/"></script>
<script nonce="">  // Create a Stripe client.
  var stripe = Stripe("pk_test_51Kv3H7F9rOqnI31cjxHSex5CZSO01Do3RZ7aof0e0O1zycBfVsCTOuP8snxJsqBvZfbrCM2F579Pw68JDW0SU3Cd00qCmnozPG");
  console.log(stripe)
  // Create an instance of Elements.
  var elements = stripe.elements();

  // Custom styling can be passed to options when creating an Element.
  // (Note that this demo uses a wider set of styles than the guide below.)
  var style = {
    base: {
      color: '#32325d',
      fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aab7c4'
      }
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
  };

  // Create an instance of the card Element.
  var card = elements.create('card', { style: style });

  // Add an instance of the card Element into the `card-element` <div>.
  card.mount('#card-element');

  // Handle real-time validation errors from the card Element.
  card.addEventListener('change', function (event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });

  // Handle form submission.
  var form = document.getElementById('stripe-form');
  form.addEventListener('submit', function (event) {
    event.preventDefault();

    stripe.createToken(card).then(function (result) {
      if (result.error) {
        // Inform the user if there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
      }
    });
  });

  // Submit the form with the token ID.
  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('stripe-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form
    form.submit();
  }

  var currentCardForm = $('.current-card-form');
  var newCardForm = $('.new-card-form');
  var use_default_card = document.querySelector("input[name=use_default_card]");
  use_default_card.addEventListener('change', function () {
    if (this.checked) {
      newCardForm.hide();
      currentCardForm.show()
    } else {
      newCardForm.show();
      currentCardForm.hide()
    }
  })

</script>

</script>

</script> {% endblock %}

templates/product.html
{% extends 'base.html' %}
{%block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{item.image.url}}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{object.get_category_display}}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{object.price}}</del>
              </span>
              <span>${{object.discount_price}}</span>

              {% else %}
              <span>${{object.price}}</span>
              {% endif %}
            </p>

            {%if object.description %}
            <p class="lead font-weight-bold">Description</p>
            <p> {{object.description }} </p>
            {% endif %}

            {% if user.is_authenticated%}

            <form action="{% url 'sales:add-to-cart' slug=object.slug%}" class="" method="POST">
              <!-- Default input -->
              {% csrf_token %}
              <input type="number" name= "quantity" value="1" aria-label="Search" class="" style="width: 100px">
              <button class="btn btn-primary" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

               <!-- Default input -->
              <a class="btn btn-primary"
                 href = "{% url 'sales:remove-from-cart' slug=object.slug%}">
                Remove from cart
               <i class="fas fa-shopping-cart ml-1"></i>
              </a>

            </form>
            {% else %}
              <a href="{% url 'login' %}"> Login in and buy  </a>
            {% endif %}



          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
    </div>
  </main>
  <!--Main layout-->

{% endblock %}